project:
  type: website

website:
  title: "shambolics"
  site-url: https://jstonge.quarto.pub/shambolics/
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/jstonge
      - icon: twitter
        href: https://twitter.com/_jsto
format:
  html:
    grid: 
      body-width: 1100px
    theme: theme.scss
